---
title: "preliminary analysis"
author: "Samah"
date: "2024-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)

source(here("packages.R"))
source(here("preprocessing.R"))
```

linear regresson
#complex model: random intercepts and slopes
```{r}
# shape ~ age * function_condition + (1+function_condition | participant) + (1+condition_condition | item)


summary(lmer(b_response ~ age_mo*condition + (1+condition|kidid) + (1+condition| standardlabel), data = df))

glmer(b_response ~ age_mo*condition + (1+condition|kidid) + (1+condition| standardlabel), 
      family = binomial(link = "logit"), data = df)


```
#only random intercepts

``` {r}
summary(lmer(b_response ~ age_mo*condition + (1|kidid) + (1| standardlabel), data = df))

summary(lmer(b_response ~ mean_age*condition + (1|kidid) + (1| standardlabel), data = df))

```

```{r finalmodel}

model <- glmer(b_response ~ mean_age * condition + (1 | kidid) + (1 | standardlabel),
      family = binomial(link = "logit"), data = df)
model
confint(model, method = "profile") # Profile likelihood method


```

random intercepts for only one level 

```{r}
summary(lmer(b_response ~ mean_age*condition + (1|kidid) , data = df))
summary(lmer(b_response ~ mean_age*condition + (1| standardlabel), data = df))
```

